server:
  port: 8001
spring:
  rabbitmq:
    #虚拟host 可以不设置,使用server默认host 这里暂不设置
    virtual-host: /
    host: 127.0.0.1
    port: 5672
    username: admin
    password: password
    #开启消息二次确认，开启消息生产者到交换机的确认机制。可靠性投递
    #publisher-confirms: true
    listener:
      simple:
        #消费者的最小数量
        concurrency: 1
        #消费者的最大数量
        max-concurrency: 3
        #每次获取消息的数量
        prefetch: 1
        #手动签收
        acknowledge-mode: manual
    #开启消息二次确认，开启交换机到队列的确认机制。可靠性投递
    #publisher-returns: true
    #为true，则交换机投递消息到队列失败时，则会返回给生产者
    #template:
      #mandatory: true